### ISSUE TITLE
Getting historical data for other minutes with mPulseAPI.getTimersMetrics

### ISSUE THREAD

**Issue by cleedus** [akamai/mPulseAPI.jl#10]
I see that the method "getTimersMetrics(token, appKey)" returns data for 1 minute interval. If you need data for every 5 min or 1 hour for the last 24 hours, how will you get this? I'm working on something very similar. Using this query:
"https://mpulse.soasta.com/concerto/mpulse/api/v2/ANYDU-8VSVE-ZBBD3-998BR-HKLUC/timers-metrics?date-comparator=Last24Hours&timer=TimeToInteractive&timer=PageLoad&page-group=MyPage&percentile=90&interval=5_min&format=json"
I get 1440 records of data. For 5 min interval, I should be  getting 288 records, which tells me that the above query is wrong. I have tried using "dimension-over-time" parameter, but I'm only getting data for pageLoad, and the data returned is not consistent. I'll appreciate any help on this.

**Comment by bluesmoon** [comment]
Hi @cleedus, sorry for not responding earlier, I've only just seen this.  I'm afraid this project is just a wrapper around the REST API, so if it's not possible via the REST API, then it's also not possible from the Julia binding.
I do not see `interval` listed in the REST API docs as a valid parameter, so my guess is that this cannot be done: https://techdocs.akamai.com/mpulse/reference/get-timers-metrics
