### ISSUE TITLE
fieldnames being set with incorrect values

### ISSUE THREAD

**Issue by amsingh17** [akamai/mPulseAPI.jl#5]
Field names for "Custom Metrics" and "Custom Timers" are being set to the incorrect names. 

For example: 
A custom metric named "Conversion." with index 4, and using the following code:
`domain["custom_metrics"]["Conversion."]["fieldname"]`
 should map to `custommetric4`, but is being mapped to `custom_metrics_4`.

Likewise, a custom timer named "TTI" with index 9, and using the following code:
`domain["custom_timers"]["TTI"]["fieldname"]`
 should map to `customtimer9`, but is being mapped to `timers_custom9 `.

**Comment by bluesmoon** [comment]
This is now fixed
